name = "eris"
main = "dist/_worker.js"
pages_build_output_dir = "dist"
workers_dev = false
preview_urls = false

routes = [{ pattern = "eris.krishg.com", custom_domain = true }]

compatibility_flags = ["nodejs_compat"]

[assets]
html_handling = "drop-trailing-slash"
not_found_handling = "404-page"

[observability.logs]
enabled = true

[vars]
ORIGIN = "https://eris.krishg.com"
BUN_VERSION = "1.2.17"
