compatibility_flags = [
  "nodejs_compat",
  "nodejs_als",
  "global_fetch_strictly_public",
]
compatibility_date = "2025-05-27"

name = "eris"
pages_build_output_dir = "dist"

placement.mode = "smart"

[vars]
ORIGIN = "https://eris.krishg.com"
BUN_VERSION = "1.2.17"
