name = "eris"
main = "dist/_worker.js"
workers_dev = true
preview_urls = true

routes = [{ pattern = "eris.krishg.com", custom_domain = true }]

[assets]
html_handling = "drop-trailing-slash"
not_found_handling = "404-page"

[observability.logs]
enabled = true

[vars]
BUN_VERSION = "1.2.17"
