name = "eris"

[env.production]
name = "eris"

[env.preview]
name = "eris-preview"

# Development configuration
[dev]
local_protocol = "http"
upstream_protocol = "https"
port = 5173

# Environment variables (add your own as needed)
[vars]
# ENVIRONMENT = "production"
